export const brand = {
  name: "Orivana",
  tagline: "A House of Mediterranean Craft",
  description:
    "A luxury heritage food house — premium dates, cold-pressed olive oil, and raw honey from Mediterranean lands.",
  heroCta: "Explore the Collection",
  featuredHarvestLabel: "Featured Harvest",
  featuredHarvestTitle: "The Harvest of Al Kufra",
  featuredHarvestDiscover: "Discover Selection",
  featuredHarvestAdd: "Add to Harvest",
  collectionsTitle: "Curated Harvests",
  collectionsCaption: "Collections",
  collectionsLandingTitle: "Curated Collections",
  collectionsLandingDescription:
    "Four permanent worlds within the House of Orivana — enter each collection as you would a room in a Mediterranean estate.",
  discoverSelection: "Discover Selection",
  refineSelection: "Refine Selection",
  exploreCollection: "Explore the Collection",
  completeYourSelection: "Complete Your Selection",
  culinaryJournal: "Culinary Journal",
  previousSelections: "Previous Selections",
  savedSelections: "Saved Selections",
  curatedGiftCollection: "Curated Gift Collection",
  journalTitle: "The Harvest Journal",
  journalSubtitle: "Stories of Land & Tradition",
  harvestCircle: "Inner Circle",
  harvestCircleJoin: "Join the Inner Circle",
  innerCircleLogin: "Inner Circle Login",
  harvestCircleDescription:
    "A private trade and luxury membership ecosystem — access seasonal harvests, tiered pricing, and curated allocations from Orivana.",
  harvestCircleBenefits: [
    "Early access to seasonal harvests",
    "Private harvest allocations",
    "Tiered pricing for professional kitchens",
  ],
  innerCircleProfile: "Inner Circle Profile",
  innerCircleHub: "Inner Circle Hub",
  innerCircleLandingTitle: "The Inner Circle",
  innerCircleLandingSubtitle:
    "A private agricultural guild for those who source at the rhythm of the land.",
  tiers: {
    individual: {
      name: "Individual",
      tagline: "Access Seasonal Harvests",
      description:
        "For luxury retail customers and private buyers — full retail access, seasonal drops, recipes, and journal content.",
      cta: "Join",
      access: [
        "Full retail collection",
        "Seasonal drops & private allocations",
        "Harvest recipes & journal",
      ],
    },
    restaurant: {
      name: "Restaurant",
      tagline: "Professional Kitchen Access",
      description:
        "For restaurants, chefs, hotels, and cafés — restaurant pricing, bulk ordering, and priority seasonal allocation.",
      cta: "Apply",
      access: [
        "Restaurant pricing (15% below retail)",
        "Case-based bulk purchasing",
        "Chef Supply Mode & reorder tools",
        "Origin transparency for every harvest",
      ],
    },
    wholesale: {
      name: "Wholesale",
      tagline: "Trade Access Portal",
      description:
        "For distributors, import/export companies, and retailers — wholesale pricing, high-volume ordering, and trade allocation.",
      cta: "Apply",
      access: [
        "Wholesale pricing tiers",
        "High-volume & pallet ordering",
        "Request invoice & quotation flow",
        "Export documentation requests",
      ],
    },
  },
  applicationPending: "Application Under Review",
  applicationPendingDescription:
    "Your application has been received. Our team will review your details and confirm your access shortly.",
  applicationSubmitted: "Application Submitted",
  chefSupplyMode: "Chef Supply Mode",
  chefSupplyModeDescription:
    "Enable case quantities and bulk pack suggestions throughout the harvest market.",
  tradeBasket: "Trade Allocation Request",
  chefSupplyBasket: "Chef Supply Basket",
  requestInvoice: "Request Invoice",
  requestQuotation: "Request Quotation",
  completeSupplyOrder: "Complete Supply Order",
  reorderLastSupply: "Reorder Last Supply",
  exclusiveHarvests: "Exclusive Harvests",
  harvestMarket: "Harvest Market",
  bulkOrderTool: "Bulk Order Tool",
  reorderCenter: "Reorder Center",
  lockedProduct: "Inner Circle Exclusive",
  tradeOnlyProduct: "Trade Access Required",
  requestPricingSheet: "Request Pricing Sheet",
  downloadCatalog: "Download Product Catalog",
  accountManagerRequest: "Request Account Manager",
  shopTitle: "The Collection",
  shopDescription: "Premium dates, olive oil, and raw honey — sourced at the rhythm of the seasons.",
  harvestSelection: "Harvest Selection",
  addToHarvest: "Add to Harvest",
  addedToHarvest: "Added to Harvest",
  completeSelection: "Complete Your Selection",
  harvestSelectionEmpty: "Your harvest selection is empty. Explore the collection to begin.",
  checkoutUnavailable: "Checkout unavailable",
  checkoutConfigureHint:
    "Storefront API is not connected. In Vercel, set SHOPIFY_STOREFRONT_ACCESS_TOKEN to your Headless Private Storefront token (not an Admin shpat_ token).",
  recipesTitle: "Harvest Recipes",
  recipesSubtitle: "Culinary Stories from the Land",
  recipesProductHeading: "Recipes with this ingredient",
  recipesUsedIn: "Used in this recipe",
  recipesAddAll: "Add All Ingredients to Harvest",
  recipesFooterCta: "Bring this harvest into your kitchen",
  recipesViewAll: "View all recipes",
} as const;
